openapi: 3.0.1

paths:

  /meta:

    get:
      tags:
      - "meta"
      summary: Get entire meta data object
      responses:
         200:
           description: All meta data of this document in single object
    patch:
      tags:
      - "meta"
      summary: Update entire meta data object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: All meta data of this document in single object

  /meta/{attribute}:
    get:
      tags:
      - "meta"
      summary: Get specfic meta data field
      parameters:
        - name: attribute
          in: path
          description: Name of field
          required: true
          schema: {}
      responses:
        200:
          description: Meta data content

    put:
      tags:
      - "meta"
      summary: Set specfic meta data field
      parameters:
        - name: attribute
          in: path
          description: Name of field
          required: true
          schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              type: string

    delete:
      tags:
      - "meta"
      summary: Delete specfic meta data field
      parameters:
        - name: attribute
          in: path
          description: Name of the meta data field
          required: true
          schema: {}
      responses:
        200:
          description: 

 
  /file/:
    get:
      tags:
      - "file"
      summary: List all files
      responses:
       200:
         description: List of files and urls associated with this document
 
  /file/{path}:
    get:
      tags:
      - "file"
      summary: Get download url for path
      parameters:
      - name: path
        in: path
        description: local path to file
        required: false
        format: uri
      responses:
        200:
          description: path and download url
         
    delete:
      tags:
      - "file"
      summary: Delete file at path
      parameters:
      - name: path
        in: path
        description: local path to file
        required: true
        format: uri
      responses:
        200:
          description:

    post:
      tags:
      - "file"
      summary: Get upload url for path
      parameters:
      - name: path
        in: path
        description: local path to file
        required: false
        format: uri
      responses:
        200:
          description: path and upload url
         
  /load:
    post:
      tags:
      - "document"
      summary: Get complete document and meta data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: All meta data of this document in single object

  /refresh:
    get:
      tags:
      - "document"
      summary: Refresh document token
      responses:
         200:
           description: All meta data of this document in single object
          
components: {}
